# Generated by Django 3.2.7 on 2021-09-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0002_auto_20210929_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='description',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='pic',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
